### ISSUE TITLE
Error Invalid proto descriptor

### ISSUE THREAD

**Issue by meenanegi** [spaceone-dev/grpc_requests#18]
**Describe the bug**
New to grpc and seeing this error when i try to use this library

**To Reproduce**
>>> from grpc_requests import Client
>>> m=Client.get_by_endpoint(endpoint)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mnegi/grpcCEnv2/lib/python3.8/site-packages/grpc_requests/client.py", line 56, in get_by_endpoint
    _cached_clients[endpoint] = cls(endpoint, **kwargs)
  File "/Users/mnegi/grpcCEnv2/lib/python3.8/site-packages/grpc_requests/client.py", line 297, in __init__
    self.register_all_service()
  File "/Users/mnegi/grpcCEnv2/lib/python3.8/site-packages/grpc_requests/client.py", line 208, in register_all_service
    self.register_service(service)
  File "/Users/mnegi/grpcCEnv2/lib/python3.8/site-packages/grpc_requests/client.py", line 345, in register_service
    self._register_file_descriptor(file_descriptor)
  File "/Users/mnegi/grpcCEnv2/lib/python3.8/site-packages/grpc_requests/client.py", line 339, in _register_file_descriptor
    self._desc_pool.Add(file_descriptor)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "grpc/reflection/v1alpha/reflection.proto":
  grpc.reflection.v1alpha.ServerReflectionRequest.message_request: "grpc.reflection.v1alpha.ServerReflectionRequest.message_request" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionRequest.host: "grpc.reflection.v1alpha.ServerReflectionRequest.host" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionRequest.file_by_filename: "grpc.reflection.v1alpha.ServerReflectionRequest.file_by_filename" is already defined in file "grpc_reflection/v1alpha/reflection.proto".

pip freeze:

cachetools==4.2.0
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
google-api-core==1.25.0
google-auth==1.24.0
googleapis-common-protos==1.52.0
grpc-requests==0.0.9
grpcio==1.34.0
grpcio-reflection==1.34.0
idna==2.10
protobuf==3.14.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pytz==2020.5
requests==2.25.1
rsa==4.7
six==1.15.0
urllib3==1.26.3

**Comment by meenanegi** [comment]
@wesky93 Any clue what might be wrong here ?

**Comment by wesky93** [comment]
I think we need to explain the reflection first.
Originally, grpc can communicate only if both servers and clients have the same proto file. However, if the server supports the Reflection service, the client can receive the required proto file as the Reflection service.
The client then registers with the DB that keeps the proto file to use the downloaded proto file. Although the reflection service is also grpc-based, it is automatically registered with the DB in situations where you download and import the proto file through the pypi, enabling communication. This means that the client communicates with the Reflection service in a situation where the client already has a Reflection proto. However, if you try to register duplicate protofile in DB that manages proto, you will get an error as you showed.
On the grpc server, you can set which service's proto file to be delivered through the reflection service, which seems to have been set to be delivered by yourself.
So the client would receive a reflection proto file.
In the long run, even if the server accidentally sends a reflection file, it should be set to ignore it. Until I do that, you should remove the setting to add the reflector service once you register the services that will be exposed to the reflection service on the server.
This sentence is written through a translator so you can hug it smoothly. Please excuse me.

**Comment by wesky93** [comment]
@alterhu2020 @meenanegi  The underlying cause is to reflect unnecessary files on the server, but in the end, the client can't control them, so fixing the server doesn't seem to be the solution.
So, I will add a function that prevents synchronization of well-known proto-buffer files such as reflection or files that users want. However, this feature does not have the exact same proto-buffer file as the server, and in some cases requests may not be processed properly.
However, I'm busy recently, so I don't think it'll be possible to change it quickly.
So if you can get a proto-buffer file on the server side,
I recommend using the StubClient.

**Comment by wesky93** [comment]
fix in #30
