### ISSUE TITLE
Invalid proto descriptor for file "reflection/grpc_reflection_v1alpha/reflection.proto"

### ISSUE THREAD

**Issue by ArturFazlyev** [spaceone-dev/grpc_requests#28]
I get this error when I create a client

from grpc_requests import Client

client = Client.get_by_endpoint("localhost:82")
print(client.service_names)

TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "reflection/grpc_reflection_v1alpha/reflection.proto":
  grpc.reflection.v1alpha.ServerReflectionRequest.message_request: "grpc.reflection.v1alpha.ServerReflectionRequest.message_request" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionRequest.host: "grpc.reflection.v1alpha.ServerReflectionRequest.host" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionRequest.file_by_filename: "grpc.reflection.v1alpha.ServerReflectionRequest.file_by_filename" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionRequest.file_containing_symbol: "grpc.reflection.v1alpha.ServerReflectionRequest.file_containing_symbol" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionRequest.file_containing_extension: "grpc.reflection.v1alpha.ServerReflectionRequest.file_containing_extension" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionRequest.all_extension_numbers_of_type: "grpc.reflection.v1alpha.ServerReflectionRequest.all_extension_numbers_of_type" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionRequest.list_services: "grpc.reflection.v1alpha.ServerReflectionRequest.list_services" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionRequest: "grpc.reflection.v1alpha.ServerReflectionRequest" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ExtensionRequest.containing_type: "grpc.reflection.v1alpha.ExtensionRequest.containing_type" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ExtensionRequest.extension_number: "grpc.reflection.v1alpha.ExtensionRequest.extension_number" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ExtensionRequest: "grpc.reflection.v1alpha.ExtensionRequest" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionResponse.message_response: "grpc.reflection.v1alpha.ServerReflectionResponse.message_response" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionResponse.valid_host: "grpc.reflection.v1alpha.ServerReflectionResponse.valid_host" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionResponse.original_request: "grpc.reflection.v1alpha.ServerReflectionResponse.original_request" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionResponse.file_descriptor_response: "grpc.reflection.v1alpha.ServerReflectionResponse.file_descriptor_response" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionResponse.all_extension_numbers_response: "grpc.reflection.v1alpha.ServerReflectionResponse.all_extension_numbers_response" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionResponse.list_services_response: "grpc.reflection.v1alpha.ServerReflectionResponse.list_services_response" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionResponse.error_response: "grpc.reflection.v1alpha.ServerReflectionResponse.error_response" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionResponse: "grpc.reflection.v1alpha.ServerReflectionResponse" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.FileDescriptorResponse.file_descriptor_proto: "grpc.reflection.v1alpha.FileDescriptorResponse.file_descriptor_proto" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.FileDescriptorResponse: "grpc.reflection.v1alpha.FileDescriptorResponse" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ExtensionNumberResponse.base_type_name: "grpc.reflection.v1alpha.ExtensionNumberResponse.base_type_name" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ExtensionNumberResponse.extension_number: "grpc.reflection.v1alpha.ExtensionNumberResponse.extension_number" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ExtensionNumberResponse: "grpc.reflection.v1alpha.ExtensionNumberResponse" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ListServiceResponse.service: "grpc.reflection.v1alpha.ListServiceResponse.service" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ListServiceResponse: "grpc.reflection.v1alpha.ListServiceResponse" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServiceResponse.name: "grpc.reflection.v1alpha.ServiceResponse.name" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServiceResponse: "grpc.reflection.v1alpha.ServiceResponse" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ErrorResponse.error_code: "grpc.reflection.v1alpha.ErrorResponse.error_code" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ErrorResponse.error_message: "grpc.reflection.v1alpha.ErrorResponse.error_message" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ErrorResponse: "grpc.reflection.v1alpha.ErrorResponse" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflection.ServerReflectionInfo: "grpc.reflection.v1alpha.ServerReflection.ServerReflectionInfo" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflection: "grpc.reflection.v1alpha.ServerReflection" is already defined in file "grpc_reflection/v1alpha/reflection.proto".
  grpc.reflection.v1alpha.ServerReflectionRequest.file_containing_extension: "grpc.reflection.v1alpha.ExtensionRequest" seems to be defined in "grpc_reflection/v1alpha/reflection.proto", which is not imported by "reflection/grpc_reflection_v1alpha/reflection.proto".  To use it here, please add the necessary import.
  grpc.reflection.v1alpha.ServerReflectionResponse.original_request: "grpc.reflection.v1alpha.ServerReflectionRequest" seems to be defined in "grpc_reflection/v1alpha/reflection.proto", which is not imported by "reflection/grpc_reflection_v1alpha/reflection.proto".  To use it here, please add the necessary import.
  grpc.reflection.v1alpha.ServerReflectionResponse.file_descriptor_response: "grpc.reflection.v1alpha.FileDescriptorResponse" seems to be defined in "grpc_reflection/v1alpha/reflection.proto", which is not imported by "reflection/grpc_reflection_v1alpha/reflection.proto".  To use it here, please add the necessary import.
  grpc.reflection.v1alpha.ServerReflectionResponse.all_extension_numbers_response: "grpc.reflection.v1alpha.ExtensionNumberResponse" seems to be defined in "grpc_reflection/v1alpha/reflection.proto", which is not imported by "reflection/grpc_reflection_v1alpha/reflection.proto".  To use it here, please add the necessary import.
  grpc.reflection.v1alpha.ServerReflectionResponse.list_services_response: "grpc.reflection.v1alpha.ListServiceResponse" seems to be defined in "grpc_reflection/v1alpha/reflection.proto", which is not imported by "reflection/grpc_reflection_v1alpha/reflection.proto".  To use it here, please add the necessary import.
  grpc.reflection.v1alpha.ServerReflectionResponse.error_response: "grpc.reflection.v1alpha.ErrorResponse" seems to be defined in "grpc_reflection/v1alpha/reflection.proto", which is not imported by "reflection/grpc_reflection_v1alpha/reflection.proto".  To use it here, please add the necessary import.
  grpc.reflection.v1alpha.ListServiceResponse.service: "grpc.reflection.v1alpha.ServiceResponse" seems to be defined in "grpc_reflection/v1alpha/reflection.proto", which is not imported by "reflection/grpc_reflection_v1alpha/reflection.proto".  To use it here, please add the necessary import.
  grpc.reflection.v1alpha.ServerReflection.ServerReflectionInfo: "grpc.reflection.v1alpha.ServerReflectionRequest" seems to be defined in "grpc_reflection/v1alpha/reflection.proto", which is not imported by "reflection/grpc_reflection_v1alpha/reflection.proto".  To use it here, please add the necessary import.
  grpc.reflection.v1alpha.ServerReflection.ServerReflectionInfo: "grpc.reflection.v1alpha.ServerReflectionResponse" seems to be defined in "grpc_reflection/v1alpha/reflection.proto", which is not imported by "reflection/grpc_reflection_v1alpha/reflection.proto".  To use it here, please add the necessary import.

**Name: grpc-requests**
Version: 0.0.10
Summary: grpc for Humans. grpc reflection support client
Home-page: https://github.com/spaceone-dev/grpc_requests
Author: None
Author-email: None
License: Apache License 2.0
Location: c:\git\item-stock-service-test\venv\lib\site-packages
Requires: grpcio, google-api-core, click, grpcio-reflection
Required-by:

**Comment by wesky93** [comment]
It seems that some servers have also released the reflection service as reflection.
I think when registering a proto file through reflection, certain files can be modified to prevent synchronization.

**Comment by wesky93** [comment]
fix in #30
